# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
# build.os : https://docs.readthedocs.io/en/stable/config-file/v2.html#build-os
build:
  os: ubuntu-22.04  
  tools:
    python: "3.7"  # bc that is what it seems to use right now...

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py
  
# If using Sphinx, optionally build your docs in additional formats such as PDF
formats:
   - pdf
   - epub

# We recommend specifying your dependencies to enable reproducible builds:
# https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
# python:
#   install:
#   - requirements: docs/requirements.txt
